<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MSTest" Version="4.2.3"/>
        <PackageReference Include="Testcontainers" Version="4.15.0"/>
        <PackageReference Include="Testcontainers.MongoDb" Version="4.15.0"/>
        <PackageReference Include="TUnit" Version="1.66.27"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting"/>
    </ItemGroup>

</Project>
